### ISSUE TITLE
nothing happening / API connection problem

### ISSUE THREAD

**Issue by jedateach** [silverstripe-droptables/silverstripe-drupal-connector#10]
I'm raising this issue to find out the current status of the drupal connector module. I've loaded it up in a 3.1 site, and when I run the import for a DrupalMenuContentSource, I just get a success message, and nothing else.

I'm working on fixes, and introducing some logging, but if there is any extra background that can be provided, that would be great.

**Comment by ghost** [comment]
I've used the connector recently successfully, though I've found that it often needs tweaking on a per-site basis as it hasn't been tested on a wide variety of installs.

Are the pages from the Drupal site displayed in the tree in the external content tab? Or can you just see the menu content source there?

**Comment by jedateach** [comment]
My main issue is that after clicking "Start importing", I get a success message, and nothing else happens. No tree, nothing imported, just as if I hadn't clicked the import button.

**Comment by jedateach** [comment]
Ah, just had a breakthrough: API connection issue

   [Error] Access denied for user anonymous

Should I be entering API key/domain for drupal 7?

**Comment by ghost** [comment]
No, Drupal 7 shouldn't require an API key. Really, those options should get removed when you select Drupal 7.

That sounds like a problem with the user privileges. The anonymous user won't have the rights to use the menu service. So you can either set up an importer user and give them the proper rights, or (if it's just a site stored locally) give the anon user those rights.

**Comment by jedateach** [comment]
Yep, allowing access for anonmyous user was the solution. Thanks Robert!

**Comment by ghost** [comment]
No problem! It'd be great to get your feedback about using it, it's still rough around the edges and could do with a lot of usability improvements.

Like accurate error messages... :)
